server:
  port: 8010

datasource:
  driverName: mysql
  host: rm-2zeh286g9l5sp7i76yo.mysql.rds.aliyuncs.com
  port: 3306
  database: hangguanli
  username: myroot
  password: HangGuanLiRoot00
  charset: utf8